# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inscategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='\u5236\u5ea6\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u5236\u5ea6\u5206\u7c7b',
                'verbose_name_plural': '\u5236\u5ea6\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50, verbose_name='\u5236\u5ea6\u5185\u5bb9')),
                ('institutionid', models.CharField(max_length=10, verbose_name='\u5236\u5ea6ID')),
                ('score', models.CharField(max_length=2, verbose_name='\u52a0\u6263\u5206')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.inscategory', verbose_name='\u5236\u5ea6\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u5236\u5ea6',
                'verbose_name_plural': '\u5236\u5ea6',
            },
        ),
    ]
