# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-16 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 5, 16, 10, 7, 41, 344000), max_length=50, verbose_name='\u5236\u5ea6\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
