# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institution_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.inscategory', verbose_name='\u6240\u5c5e\u5c97\u4f4d\u804c\u8d23'),
        ),
    ]
