# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-13 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informationinputs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='is_informationinput',
            fields=[
            ],
            options={
                'verbose_name': '\u5ba1\u6838\u5ba1\u6279',
                'proxy': True,
                'verbose_name_plural': '\u5ba1\u6838\u5ba1\u6279',
            },
            bases=('informationinputs.informationinput',),
        ),
        migrations.CreateModel(
            name='pro_informationinput',
            fields=[
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5458\u6d41\u7a0b\u8865\u6551',
                'proxy': True,
                'verbose_name_plural': '\u7ba1\u7406\u5458\u6d41\u7a0b\u8865\u6551',
            },
            bases=('informationinputs.informationinput',),
        ),
        migrations.AlterField(
            model_name='informationinput',
            name='image',
            field=models.ImageField(default='information/default.png', max_length=1000, upload_to='information/%y/%m'),
        ),
        migrations.AlterField(
            model_name='informationinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8003\u6838\u5458'),
        ),
    ]
