# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationinputs', '0002_auto_20170613_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationinput',
            name='category',
            field=models.CharField(choices=[('gd', '\u5de5\u6bb5'), ('bz', '\u73ed\u7ec4'), ('gr', '\u4e2a\u4eba')], default='gr', max_length=20, verbose_name='\u8003\u6838\u5bf9\u8c61\u7c7b\u522b'),
        ),
    ]
